sudo: no

language: python

cache: pip

python:
- '2.7'
- '3.3'
- '3.4'

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
- nosetests
- mincss https://news.ycombinator.com

branches:
  only:
    - master

deploy:
  provider: pypi
  user: peterbe
  password:
    secure: MWefB3EHYL8Nsoq0Fy0w+V0OFAOM4PKmYXxkYN/BAoMAYUTFbPm0CCNnafl72aQAKJkyuHXsYQf3dqRMtSPVkzMYJfniZ+LBxouk36v5+f2OXuMaSiLUug3nBAnNhMIyverWBBghF53IaKowyB/FzqC00U006K5aUzE6dFWEhF4=
  on:
    repo: peterbe/mincss
  distributions: "sdist bdist_wheel"
