sudo: no

language: python

cache:
  # Apparently if you override the install command that silently disables the
  # cache: pip support. This is less than ideal and I've opened up
  # travis-ci/travis-ci#3239 to hopefully get that addressed. For now I'll
  # manually add the pip cache directory to the build cache.
  directories:
    - ~/.cache/pip

env:
  global:
    # These two environment variables could be set by Travis itself, or Travis
    # could configure itself in /etc/, ~/, or inside of the virtual
    # environments. In any case if these two values get configured then end
    # users only need to enable the pip cache and manually run pip wheel before
    # running pip install.
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
- '2.7'
- '3.3'
- '3.4'

install:
  # Before installation, we'll run ``pip wheel``, this will build wheels for
  # anything that doesn't already have one on PyPI.
  - pip wheel -r requirements.txt
  # Actually install our dependencies now, this will pull from the directory
  # that the first command placed the Wheels into.
  - pip install -r requirements.txt
  # we also need to install the test dependencies
  - python setup.py install

script:
- nosetests
- mincss https://news.ycombinator.com

branches:
  only:
    - master

deploy:
  provider: pypi
  user: peterbe
  password:
    secure: MWefB3EHYL8Nsoq0Fy0w+V0OFAOM4PKmYXxkYN/BAoMAYUTFbPm0CCNnafl72aQAKJkyuHXsYQf3dqRMtSPVkzMYJfniZ+LBxouk36v5+f2OXuMaSiLUug3nBAnNhMIyverWBBghF53IaKowyB/FzqC00U006K5aUzE6dFWEhF4=
  on:
    repo: peterbe/mincss
  distributions: "sdist bdist_wheel"
